spring.application.name=order-service

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost/orders

spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-service-group
order-paid-topic=orders.event
delivery-assigned-topic=delivery.events

payment-service.base-url=http://localhost:8081